import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API=location.port==='8000'?'':'http://127.0.0.1:8000';
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(v);
async function api(path, options={}, token){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Не удалось выполнить запрос');return data}
function App(){
 const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[selected,setSelected]=useState(null),[cart,setCart]=useState([]),[user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null')),[token,setToken]=useState(()=>localStorage.getItem('token')||''),[modal,setModal]=useState(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const auth=token;
 const loadProducts=async()=>{setLoading(true);try{setProducts(await api(`/products?search=${encodeURIComponent(search)}${category?`&category=${category}`:''}`))}finally{setLoading(false)}};
 const loadCart=async()=>{if(!auth){setCart([]);return} const d=await api('/cart',{},auth);setCart(d.items)};
 useEffect(()=>{api('/categories').then(setCategories);loadProducts()},[]);useEffect(()=>{const t=setTimeout(loadProducts,200);return()=>clearTimeout(t)},[search,category]);useEffect(()=>{loadCart()},[auth]);
 const cartTotal=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.quantity,0),[cart]);
 const tell=t=>{setNotice(t);setTimeout(()=>setNotice(''),2600)};
 const add=async p=>{if(!auth){setModal('auth');return}try{await api('/cart/items',{method:'POST',body:JSON.stringify({product_id:p.id,quantity:1})},auth);await loadCart();tell('Товар добавлен в корзину')}catch(e){tell(e.message)}};
 const login=async(data,register)=>{try{const d=await api(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(data)});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));setToken(d.token);setUser(d.user);setModal(null);tell(`Рады видеть, ${d.user.name}`)}catch(e){throw e}};
 const logout=()=>{localStorage.clear();setToken('');setUser(null);setCart([]);tell('Вы вышли из аккаунта')};
 return <><header><a className="brand" href="#top">sever<span>.</span></a><nav><a href="#catalog">Каталог</a><a href="#about">О магазине</a></nav><div className="head-actions">{user?<button className="link" onClick={logout}>{user.name}</button>:<button className="link" onClick={()=>setModal('auth')}>Войти</button>}<button className="cart-btn" onClick={()=>setModal('cart')}>Корзина <b>{cart.length}</b></button></div></header>
 <main id="top"><section className="hero"><div><p className="eyebrow">Вещи для ежедневного ритма</p><h1>Меньше лишнего.<br/>Больше вашего.</h1><p className="hero-copy">Отобранные предметы для дома, работы и движения по городу.</p><a className="primary" href="#catalog">Смотреть каталог</a></div><img src="https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1400&q=85" alt="Современный интерьер"/></section>
 <section className="featured"><p>Небольшая подборка практичных предметов</p><div><b>Быстрая доставка</b><b>Возврат 14 дней</b><b>Оплата при получении</b></div></section>
 <section id="catalog" className="catalog"><div className="section-head"><div><p className="eyebrow">Каталог</p><h2>Выберите то, что останется с вами надолго</h2></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Все категории</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div></div><div className="grid">{loading?[1,2,3].map(x=><div className="skeleton" key={x}/>):products.map(p=><article className="product" key={p.id}><button className="image-btn" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/></button><div className="product-info"><span>{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div><b>{money(p.price)}</b><button onClick={()=>add(p)}>В корзину</button></div></div></article>)}</div>{!loading&&!products.length&&<div className="empty">Ничего не найдено. Попробуйте изменить запрос.</div>}</section>
 <section id="about" className="about"><div><p className="eyebrow">Sever</p><h2>Магазин без случайных вещей</h2></div><p>Мы собираем предметы, у которых есть понятная задача, спокойная форма и место в обычной жизни. Без спешки, без бесконечного выбора.</p></section></main><footer><span>sever.</span><span>Учебный проект веб витрины</span></footer>
 {notice&&<div className="toast">{notice}</div>}{selected&&<ProductModal p={selected} add={add} close={()=>setSelected(null)}/>} {modal==='auth'&&<AuthModal close={()=>setModal(null)} login={login}/>} {modal==='cart'&&<CartModal items={cart} total={cartTotal} token={auth} reload={loadCart} close={()=>setModal(null)} checkout={()=>setModal('checkout')}/>} {modal==='checkout'&&<Checkout close={()=>setModal(null)} token={auth} onDone={()=>{loadCart();setModal(null);tell('Заказ создан. Спасибо!')}}/>}</>}
function ProductModal({p,add,close}){return <div className="overlay" onMouseDown={close}><div className="modal product-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><img src={p.image} alt={p.name}/><div><span>{p.category}</span><h2>{p.name}</h2><p>{p.description}</p><b>{money(p.price)}</b><button className="primary wide" onClick={()=>add(p)}>Добавить в корзину</button></div></div></div>}
function AuthModal({close,login}){const [reg,setReg]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({name:'',email:'',password:''});const submit=async e=>{e.preventDefault();try{await login(form,reg)}catch(e){setError(e.message)}};return <div className="overlay"><form className="modal form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><h2>{reg?'Создать аккаунт':'Войти'}</h2>{reg&&<input required placeholder="Ваше имя" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Пароль" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<small className="error">{error}</small>}<button className="primary wide">{reg?'Зарегистрироваться':'Войти'}</button><button type="button" className="link switch" onClick={()=>{setReg(!reg);setError('')}}>{reg?'Уже есть аккаунт':'Создать аккаунт'}</button><small>Тестовый администратор: admin@sever.local / admin123</small></form></div>}
function CartModal({items,total,token,reload,close,checkout}){const change=async(i,q)=>{if(q<1)return;await api(`/cart/items/${i.id}`,{method:'PUT',body:JSON.stringify({quantity:q})},token);reload()};const del=async i=>{await api(`/cart/items/${i.id}`,{method:'DELETE'},token);reload()};return <div className="overlay"><div className="modal cart"><button className="close" onClick={close}>×</button><h2>Корзина</h2>{!items.length?<p>Корзина пока пуста.</p>:<>{items.map(i=><div className="cart-row" key={i.id}><img src={i.image} alt=""/><div><b>{i.name}</b><span>{money(i.price)}</span></div><div className="qty"><button onClick={()=>change(i,i.quantity-1)}>−</button>{i.quantity}<button onClick={()=>change(i,i.quantity+1)}>+</button></div><button className="remove" onClick={()=>del(i)}>×</button></div>)}<div className="total"><b>Итого</b><b>{money(total)}</b></div><button className="primary wide" onClick={checkout}>Оформить заказ</button></>}</div></div>}
function Checkout({close,token,onDone}){const [error,setError]=useState('');const submit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/orders',{method:'POST',body:JSON.stringify({phone:f.get('phone'),address:f.get('address')})},token);onDone()}catch(e){setError(e.message)}};return <div className="overlay"><form className="modal form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><h2>Оформление заказа</h2><input required name="phone" placeholder="Телефон"/><input required name="address" placeholder="Адрес доставки"/>{error&&<small className="error">{error}</small>}<button className="primary wide">Подтвердить заказ</button></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
